<?php require 'templates/plantillas_generales/header.phtml'?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

<form method='post' action='iniciar_sesion'>
    <div class='form-group'>
        <label for='usuario'>Usuario</label>
        <input type='text' class='form-control' id='usuario' name='usuario' required>
    </div>
    <div class='form-group'>
        <label for='contrasenia'>Contraseña</label>
        <input type='password' class='form-control' id='contrasenia' name='contrasenia' required>
    </div>
    <button type='submit' class='btn btn-primary'>Iniciar Sesión</button>
</form>

<?php require 'templates/plantillas_generales/footer.phtml'?>