<div class="container">
    <h1>Agregar/modificar autor</h1>
    <form>
        <div class="mb-3">
            <label for="nombreApellido" class="form-label">Nombre y apellido</label>
            <input type="text" class="form-control" id="nombreApellido">
        </div>
        <div class="mb-3">
            <label for="nacionalidad" class="form-label">Nacionalidad</label>
            <input type="text" class="form-control" id="nacionalidad">
        </div>
        <div class="mb-3">
            <label class="form-label" for="biografia">Biografia</label>
            <input type="text" class="form-control" id="biografia">
            
        </div>
        <div class="mb-3">
            <label class="form-label" for="imagenUrl">Imagen URL</label>
            <input type="text" class="form-control" id="imagenUrl">
            
        </div>
        <button type="submit" class="btn btn-success">Enviar</button>
    </form>
</div>