<?php require 'templates/plantillas_generales/header.phtml'?>

<div class="container">
    <h1><?= $autor ? 'Modificar autor' : 'Agregar autor' ?></h1>
    <form action="<?= $autor ? BASE_URL . 'editar_autor/' . $autor->id_autor : 'nuevo_autor' ?>" method="POST">
        <div class="mb-3">
            <label for="nombre_apellido" class="form-label">Nombre y apellido</label>
            <input type="text" class="form-control" id="nombre_apellido" name="nombre_apellido" value="<?= $autor ? $autor->nombre_apellido : '' ?>">
        </div>
        <div class="mb-3">
            <label for="nacionalidad" class="form-label">Nacionalidad</label>
            <input type="text" class="form-control" id="nacionalidad" name="nacionalidad" value="<?= $autor ? $autor->nacionalidad : '' ?>">
        </div>
        <div class="mb-3">
            <label class="form-label" for="biografia">Biografia</label>
            <input type="text" class="form-control" id="biografia" name="biografia" value="<?= $autor ? $autor->biografia : '' ?>">
            
        </div>
        <div class="mb-3">
            <label class="form-label" for="imagen_url">Imagen URL</label>
            <input type="text" class="form-control" id="imagen_url" name="imagen_url" value="<?= $autor ? $autor->imagen_url : '' ?>">
            
        </div>
        <button type="submit" class="btn btn-success">Enviar</button>
    </form>
</div>
<?php require 'templates/plantillas_generales/footer.phtml'?>