<div class="container">
    <h1>Agregar/modificar libro</h1>
    <form>
        <div class="mb-3">
            <label for="titulo" class="form-label">Título</label>
            <input type="text" class="form-control" id="titulo">
        </div>
        <div class="mb-3">
            <label for="genero" class="form-label">Género</label>
            <input type="text" class="form-control" id="genero">
        </div>
        <div class="mb-3">
            <label class="form-label" for="editorial">Editorial</label>
            <input type="text" class="form-control" id="editorial">
            
        </div>
        <div class="mb-3">
            <label class="form-label" for="anio">Año de Publicación</label>
            <input type="number" class="form-control" id="anio">
            
        </div>
        <div class="mb-3">
            <label class="form-label" for="sinopsis">Sinopsis</label>
            <input type="text" class="form-control" id="sinopsis">
            
        </div>
        <button type="submit" class="btn btn-success">Enviar</button>
    </form>
</div>