<?php require 'templates/plantillas_generales/header.phtml'?>

<ul class="list-group mt-4">
<?php foreach($autores as $autor): ?>
    <li class="list-group-item item-task">
        <div class="label">
            <b><?=$autor->id_autor?> | <?=$autor->nombre_apellido ?> |<?= $autor->nacionalidad ?></b>  
        </div>
        <div class="actions">
            <a href="<?= BASE_URL . 'editar_autor/' .  $autor->id_autor?>" type="button" class='btn btn-warning btn-sm ml-auto'>Modificar</a>
            <a href="<?= BASE_URL . 'eliminar_autor/' .  $autor->id_autor?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<?php require 'templates/plantillas_generales/footer.phtml'?>
