<?php require 'templates/plantillas_generales/header.phtml'?>

<div class="container">
    <h2 class="pb-4">Nuestros libros</h2>
    <div class=" row row-cols-1 row-cols-md-2 g-4">
        <?php 
            foreach($libros as $libro): ?>
            <div class="card p-2 m-2" style="width:350px; heigth:700px; display:flex; justify-content:center; align-items:center;">
                    <div class="card-body">
                        <h5 class="card-title"><?= $libro->titulo ?></h5>
                        <img src="<?= './img/portada'.$libro->id_libro.'.jpg'?>" class="card-img-top" style="width:200px; heigth:300px;" alt="imagen del libro <?= $libro->titulo ?>">
                        
                    </div>
                    <a href="#" class="btn btn-primary justify-content:flex-end;">ver detalle</a>
            </div>
        <?php 
        endforeach ?>
    </div>
</div>

<?php require 'templates/plantillas_generales/footer.phtml'?>