<?php require 'templates/plantillas_generales/header.phtml'?>


<ul class="list-group mt-4">
<?php foreach($libros as $libro): ?>
    <li class="list-group-item item-task">
        <div class="label">
            <b><?=$libro->id_libro?> | <?=$libro->titulo ?> |<?= $libro->genero ?> | <?= $libro->editorial ?> |<?= $libro->anio_publicacion ?>
            <?= $libro->sinopsis ?> | <?= $libro->autor->nombre_apellido ?></b>  
        </div>
        <div class="actions">
            <a href="editar_libro/<?= $libro->id_libro?>" type="button" class='btn btn-warning btn-sm ml-auto'>Modificar</a>
            <a href="eliminar_libro/<?= $libro->id_libro?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<?php require 'templates/plantillas_generales/footer.phtml'?>
