<?php require 'templates/plantillas_generales/header.phtml'?>

<div class="container">
    <h2 class="pb-4">Nuestros libros</h2>
    <div class=" row row-cols-md-4 g-4">
        <?php 
            foreach($libros as $libro): ?>
            <div class="card p-2 m-2 ">
                    <div class="card-body card-libro">
                        <h5 class="card-title"><?= $libro->titulo ?></h5>
                        <img src="<?= BASE_URL .'./img/portada'. $libro->id_libro.'.jpg'?>" alt="imagen del libro <?= $libro->titulo ?>">
                        <h6 class="card-subtitle"><?= $libro->autor->nombre_apellido ?></h6>
                    </div>
                    <a href="<?= BASE_URL . 'libro/' . $libro->id_libro ?>"  class="btn btn-primary">ver detalle</a> 
                    
            </div>
        <?php 
        endforeach ?>
    </div>
</div>

<?php require 'templates/plantillas_generales/footer.phtml'?>