
<?php require 'templates/plantillas_generales/header.phtml'?>
<ul class="list-group ">
<h2>Nuestro Autor</h2>
<?php $id_autor ?>
    <li class="list-group-item m-2 item-autor">
        <div class="container-fluid ">
            <img src="<?= $autor->imagen_url?>"  class="img-thumbnail m-1" alt="img autor" srcset="">
            <a href="#" class="fs-2 m-2"><?= $autor->nombre_apellido?></a>
        </div>
        
    </li>

</ul> 
    

<?php require 'templates/plantillas_generales/footer.phtml'?>